"""Provider-neutral browser driver contract used by AnyBridge."""
from __future__ import annotations
from typing import Protocol

class BrowserDriver(Protocol):
    async def start(self, settle: float = 1.0): ...
    async def close(self): ...
    async def navigate(self, url: str): ...
    async def snapshot(self, interactive_only: bool = True, compact: bool = True, selector: str | None = None, max_chars: int = 12000): ...
    async def click_ref(self, ref: str): ...
    async def fill_ref(self, ref: str, value: str, press_enter: bool = False): ...
    async def select_ref(self, ref: str, value: str): ...
    async def press_key(self, key: str, ref: str | None = None): ...
    async def wait_for(self, selector: str | None = None, text: str | None = None, timeout_ms: int = 10000): ...
    async def extract_structured(self, schema: dict, selector: str | None = None): ...
    async def screenshot(self, full_page: bool = False): ...
    async def current_site(self) -> dict: ...
    async def list_tools(self) -> list[dict]: ...
    async def call_tool(self, name: str, arguments: dict): ...
    async def network_policy(self) -> dict: ...
    async def trust_host(self, host: str) -> dict: ...
    async def revoke_host(self, host: str) -> dict: ...
    async def click_text(self, text: str): ...
    async def fill_label(self, label: str, value: str): ...
